#!/usr/bin/env python3
"""
Create the Blood Pressure Monitoring manuscript (.docx) — English version.

All numerical results are read from results/summary.json (generated by
src/simulate.py + src/analyze.py); none are hard-coded here. References are
numbered in order of first appearance by the Citations manager.

Note on journal format: Blood Pressure Monitoring is a Lippincott (LWW)
journal. LWW journals generally require figures to be uploaded as separate
files with the legends listed in the manuscript. For ease of review this
working manuscript embeds each figure immediately after its first citation
AND lists all figure legends together; the separate figure files
(figures/*.png) and the editable figures_en.pptx are provided for the actual
Editorial Manager submission.
"""

import os
import re

from docx import Document
from docx.shared import Pt, Cm, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.oxml import OxmlElement
from docx.oxml.ns import qn

from manuscript_common import REFDB, Citations, load_summary

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
OUTDIR = os.path.join(SCRIPT_DIR, "..", "manuscripts")
OUTPATH = os.path.join(OUTDIR, "BPM_ZeroFree_Manuscript_EN.docx")
os.makedirs(OUTDIR, exist_ok=True)

S = load_summary()
C = Citations(REFDB)
P = S["parameters"]
st = S["static"]
dy = S["dynamic"]
rg = S["range_dependence"]


# ---------- number formatting helpers (values come from summary.json) ------
def f2(x):
    return f"{x:.2f}"


def f1(x):
    return f"{x:.1f}"


def f3(x):
    return f"{x:.3f}"


def ci(lo, hi, nd=3):
    return f"{lo:.{nd}f} to {hi:.{nd}f}"


def signed(x, nd=1):
    return f"{x:+.{nd}f}"


# ---------- docx setup ----------
doc = Document()
for section in doc.sections:
    section.top_margin = Cm(2.54)
    section.bottom_margin = Cm(2.54)
    section.left_margin = Cm(2.54)
    section.right_margin = Cm(2.54)

style = doc.styles["Normal"]
style.font.name = "Times New Roman"
style.font.size = Pt(12)
style.paragraph_format.line_spacing = 2.0
style.paragraph_format.space_after = Pt(0)


def add_para_with_refs(text, bold=False, italic=False, alignment=None,
                       space_after=Pt(6), font_size=Pt(12)):
    p = doc.add_paragraph()
    if alignment:
        p.alignment = alignment
    p.paragraph_format.space_after = space_after
    for part in re.split(r"(\{[^}]+\})", text):
        if part.startswith("{") and part.endswith("}"):
            run = p.add_run("[" + part[1:-1] + "]")
        else:
            run = p.add_run(part)
        run.font.name = "Times New Roman"
        run.font.size = font_size
        run.bold = bold
        run.italic = italic
    return p


def add_para(text, bold=False, italic=False, alignment=None, space_after=Pt(6)):
    return add_para_with_refs(text, bold, italic, alignment, space_after)


def add_heading_styled(text, level=1):
    h = doc.add_heading(text, level=level)
    for run in h.runs:
        run.font.name = "Times New Roman"
        run.font.color.rgb = RGBColor(0, 0, 0)
    return h


def add_eq(text):
    p = doc.add_paragraph()
    p.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = p.add_run(text)
    run.font.name = "Times New Roman"
    run.font.size = Pt(12)
    run.italic = True
    p.paragraph_format.space_after = Pt(6)


# Figures are submitted as separate files (Blood Pressure Monitoring does not
# permit figures embedded in the manuscript); only the legends appear here,
# listed together after the tables. Two figures are provided as Supplemental
# Digital Content and do not count toward the six-item figure/table limit.
FIG_LEGENDS = []
SDC_LIST = []


def add_figure(caption):
    """Register a main-text figure legend (figure numbered in order of use)."""
    FIG_LEGENDS.append(caption)


def add_sdc(caption):
    """Register a Supplemental Digital Content item."""
    SDC_LIST.append(caption)


def horizontal_borders(table):
    """Apply horizontal rules only (Blood Pressure Monitoring: no vertical rules)."""
    tblPr = table._tbl.tblPr
    borders = OxmlElement("w:tblBorders")
    for edge in ("top", "bottom", "insideH"):
        el = OxmlElement(f"w:{edge}")
        el.set(qn("w:val"), "single")
        el.set(qn("w:sz"), "4")
        el.set(qn("w:space"), "0")
        el.set(qn("w:color"), "000000")
        borders.append(el)
    for edge in ("left", "right", "insideV"):
        el = OxmlElement(f"w:{edge}")
        el.set(qn("w:val"), "none")
        borders.append(el)
    tblPr.append(borders)


# ══════════════════════════════════════════════════════════════════
# TITLE PAGE
# ══════════════════════════════════════════════════════════════════
add_para("ORIGINAL ARTICLE", bold=True, alignment=WD_ALIGN_PARAGRAPH.CENTER)
doc.add_paragraph()
title = doc.add_paragraph()
title.alignment = WD_ALIGN_PARAGRAPH.CENTER
trun = title.add_run(
    "What zeroing cannot fix: detecting residual gain and dynamic-response "
    "errors after zero calibration in invasive arterial pressure monitoring")
trun.font.name = "Times New Roman"
trun.font.size = Pt(16)
trun.bold = True
title.paragraph_format.space_after = Pt(18)

add_para("Running title: What zeroing cannot fix", italic=True,
         alignment=WD_ALIGN_PARAGRAPH.CENTER)
doc.add_paragraph()
add_para("[Author names to be completed]", alignment=WD_ALIGN_PARAGRAPH.CENTER)
add_para("[Affiliations to be completed]", alignment=WD_ALIGN_PARAGRAPH.CENTER)
doc.add_paragraph()
add_para("Corresponding author:", bold=True)
add_para("[Name, address, email, ORCID]")
doc.add_paragraph()
add_para("Word count (title page to last reference): ", space_after=Pt(0))
wc_run = doc.paragraphs[-1].add_run("[computed]")
wc_run.font.name = "Times New Roman"
wc_run.font.size = Pt(12)
add_para("Tables: 2   Figures: 4   Supplemental Digital Content: 2 figures   "
         "References: numbered in order of appearance")
doc.add_paragraph()
add_para("Keywords: ", bold=True, space_after=Pt(0))
kw = doc.paragraphs[-1]
kwr = kw.add_run(
    "arterial pressure monitoring; zero calibration; concordance correlation "
    "coefficient; Bland\u2013Altman analysis; proportional bias; dynamic "
    "response; fast-flush test; method comparison")
kwr.font.name = "Times New Roman"
kwr.font.size = Pt(12)
doc.add_paragraph()
add_para("Conflicts of Interest and Source of Funding:", bold=True,
         space_after=Pt(0))
add_para("[To be completed by the authors. State each author’s financial, "
         "consultant, institutional and other relationships and all sources "
         "of funding; if there are none, state “none declared”.]")
doc.add_page_break()

# ══════════════════════════════════════════════════════════════════
# ABSTRACT (structured, <=250 words)
# ══════════════════════════════════════════════════════════════════
add_heading_styled("Abstract", level=1)

add_para("Objective", bold=True, space_after=Pt(2))
add_para(
    "Zero calibration of an invasive arterial pressure transducer removes the "
    "direct-current (DC) offset but not sensor-gain (scale) error. We examined "
    "which of the analyses commonly reported in device-validation studies "
    "actually detect a residual gain error after zeroing, and how a "
    "frequency-dependent dynamic-response error behaves.")

add_para("Methods", bold=True, space_after=Pt(2))
add_para(
    f"Using seeded simulations we generated paired device\u2013reference "
    f"systolic pressures (n = {P['n_static']} per scenario) for four cases: "
    "offset only, ideal zeroing, uncompensated gain error, and a gain error "
    "masked by a compensating offset. Each case was assessed with the minimal "
    "Bland\u2013Altman summary (mean bias, limits of agreement), Bland\u2013Altman "
    "difference-versus-mean regression, Deming and Passing\u2013Bablok "
    "regression, and Lin\u2019s concordance correlation coefficient (CCC) with "
    "its scale-shift component. Synthetic arterial waveforms were passed "
    "through optimally-, under-, and over-damped second-order "
    "catheter\u2013transducer models.")

add_para("Results", bold=True, space_after=Pt(2))
add_para(
    f"When a 10% gain error was masked by a compensating offset, the mean "
    f"bias was {signed(st['S4_gain_masked']['bias'])} mmHg (apparently "
    "acceptable), yet the Bland\u2013Altman regression slope "
    f"({f3(st['S4_gain_masked']['prop_slope'])}), Deming slope "
    f"({f3(st['S4_gain_masked']['deming_slope'])}), Passing\u2013Bablok slope "
    f"({f3(st['S4_gain_masked']['pb_slope'])}) and CCC scale shift "
    f"(v = {f3(st['S4_gain_masked']['v'])}) all detected it. Underdamping "
    f"inflated pulse pressure by "
    f"{round((dy['underdamped_pp']['mean_ratio']-1)*100)}% and overdamping "
    f"attenuated it by {round((1-dy['overdamped_pp']['mean_ratio'])*100)}%; "
    "these errors persist after zeroing and are diagnosed by the fast-flush "
    "test. CCC rose with the sampled pressure range for one fixed device "
    f"(from {f2(rg['ccc'][0])} to {f2(rg['ccc'][-1])}).")

add_para("Conclusions", bold=True, space_after=Pt(2))
add_para(
    "A mean-bias limits-of-agreement summary can miss a clinically relevant "
    "gain error; proportional-bias\u2013aware analyses and an explicit "
    "dynamic-response check should be reported alongside it.")
doc.add_page_break()

# ══════════════════════════════════════════════════════════════════
# 1. INTRODUCTION
# ══════════════════════════════════════════════════════════════════
add_heading_styled("1. Introduction", level=1)

add_para_with_refs(
    "Invasive arterial pressure monitoring is among the most frequently "
    "performed measurements in anaesthesia and critical care. After inserting "
    "an arterial catheter, the clinician zeroes the pressure transducer to "
    "atmosphere at the level of the phlebostatic axis before monitoring "
    + C.cite("saugel2020", "saugelsessler2021") + ", and repeats zeroing "
    "whenever the height relationship between transducer and catheter changes "
    + C.cite("gupta2025") + ".")

add_para_with_refs(
    "In a fluid-filled arterial line the external transducer is connected to "
    "the catheter tip by a saline column, which introduces direct-current "
    "(DC) offsets: the hydrostatic pressure difference between transducer and "
    "measurement site, the atmospheric reference of gauge pressure, and slow "
    "transducer drift" + C.cite("mark1998", "mcghee2002") + ". Zero "
    "calibration removes all of these offsets at once.")

add_para_with_refs(
    "Zeroing, however, is purely an offset correction: it does not verify the "
    "gain (sensitivity) of the system, that is, the proportionality between a true "
    "pressure change and the displayed value. If the gain is wrong, the "
    "waveform is scaled and the error persists after zeroing. A second, "
    "frequency-dependent gain error arises from the dynamic response of the "
    "fluid-filled system: under- or over-damping distorts the pulsatile "
    "signal and therefore pulse pressure" + C.cite("gardner1981") + ".")

add_para_with_refs(
    "Zeroing nevertheless remains indispensable at the bedside, because these "
    "offsets are installation- and time-dependent physics rather than a "
    "factory-fixable device defect. The hydrostatic column depends on the "
    "height of the transducer relative to the phlebostatic axis (about "
    "7.5 mmHg per 10 cm) and changes whenever the patient or the transducer "
    "is repositioned" + C.cite("gupta2025") + "; the atmospheric gauge "
    "reference drifts with weather and altitude; and electrical or thermal "
    "drift accumulates over time" + C.cite("mark1998", "mcghee2002") + ". "
    "Detection is not the same as correction, and the two operate at different "
    "layers. Method-comparison analyses such as Bland\u2013Altman regression "
    "are retrospective validation tools that require paired reference "
    "measurements, which are not available in real time for the patient in "
    "front of the clinician; zeroing is the only procedure that removes a "
    "known, setup-specific offset a priori and without a reference. Even when "
    "a regression reveals an offset, removing it still requires zeroing. "
    "Zeroing therefore corrects offset operationally, whereas regression and "
    "CCC decomposition detect residual gain and structure, and neither can "
    "substitute for the other.")

add_para_with_refs(
    "Validation studies for arterial pressure and derived haemodynamic "
    "monitors overwhelmingly report the Bland\u2013Altman summary (mean bias "
    "and 95% limits of agreement) " + C.cite("blandaltman1986") +
    " and the Critchley percentage error " + C.cite("critchley1999") +
    ", with attention to the precision of the reference method "
    + C.cite("cecconi2009") + ". The original Bland\u2013Altman method also "
    "includes regression of the differences on the mean to detect "
    "proportional bias " + C.cite("blandaltman1999") + ", but this step is "
    "frequently omitted, and the mean-bias summary alone can be misleading "
    "when an offset and a gain error partially cancel.")

add_para_with_refs(
    "We do not claim that gain error is invisible to a properly conducted "
    "Bland\u2013Altman analysis. Rather, using a reproducible simulation, we "
    "quantify which of the analyses actually reported in the literature "
    "detect a residual gain error after zeroing, and we position Lin\u2019s "
    "concordance correlation coefficient (CCC) and its scale-shift component "
    + C.cite("lin1989", "lin2000") + ", together with Deming " +
    C.cite("linnet1990") + " and Passing\u2013Bablok " +
    C.cite("passingbablok1983") + " regression, as complementary diagnostics. "
    "We also integrate the dynamic-response (damping) error, which is specific "
    "to fluid-filled arterial lines, and discuss the range-dependence of the CCC " +
    C.cite("nickerson1997", "barnhart2007") + ".")

# ══════════════════════════════════════════════════════════════════
# 2. METHODS
# ══════════════════════════════════════════════════════════════════
add_heading_styled("2. Methods", level=1)

add_heading_styled("2.1. Arterial pressure as DC plus AC components", level=2)
add_para_with_refs(
    "An arterial pressure waveform can be decomposed into a slowly varying DC "
    "level (mean arterial pressure plus any external offset) and a pulsatile "
    "alternating-current (AC) component driven by cardiac ejection. Pulse "
    "pressure (PP = systolic [SBP] \u2212 diastolic [DBP] pressure) is a pure AC "
    "quantity and is therefore independent of any additive DC offset but "
    "proportional to sensor gain (see Figure, Supplemental Digital Content 1, "
    "which decomposes the arterial pressure signal into its DC and AC "
    "components). An offset shifts the baseline without changing PP, whereas a "
    "gain error scales the whole waveform and changes PP.")
add_sdc(
    "Supplemental Digital Content 1. Decomposition of the arterial pressure "
    "signal. (A) A DC offset shifts the baseline but leaves pulse pressure "
    "unchanged. (B) A gain error scales the entire waveform, so pulse pressure "
    "changes in proportion to the gain. Zeroing corrects the offset in (A) but "
    "cannot correct the gain error in (B).")

add_heading_styled("2.2. Statistical methods", level=2)
add_para_with_refs(
    "For each paired dataset we computed: (i) the minimal Bland\u2013Altman "
    "summary, comprising mean bias, 95% limits of agreement (mean bias \u00b1 1.96 SD) "
    "and percentage error " + C.cite("critchley1999") + "; (ii) the "
    "Bland\u2013Altman regression of the differences on the mean, whose slope "
    "tests for proportional bias " + C.cite("blandaltman1999") + "; (iii) "
    "Deming regression, which allows for error in both methods, with "
    "jackknife confidence intervals " + C.cite("linnet1990") + "; (iv) "
    "Passing\u2013Bablok non-parametric regression " +
    C.cite("passingbablok1983") + "; and (v) Lin\u2019s CCC " +
    C.cite("lin1989") + ".")

add_para_with_refs(
    "Lin\u2019s CCC (\u03c1c) decomposes as \u03c1c = r \u00d7 C_b, where r is "
    "Pearson\u2019s correlation (precision) and C_b is the bias-correction "
    "factor (accuracy) " + C.cite("lin2000") + ". C_b further decomposes as:")
add_eq("C_b = 2 / (v + 1/v + u\u00b2)")
add_para_with_refs(
    "where v = \u03c3_device/\u03c3_reference is the scale shift (the gain "
    "ratio) and u = (\u03bc_device \u2212 \u03bc_reference)/\u221a("
    "\u03c3_device\u03c3_reference) is the location shift (offset). Zeroing "
    "drives u toward zero but leaves v unchanged; a residual gain error keeps "
    "v \u2260 1 even after perfect zeroing.")

add_para_with_refs(
    "We used fixed a-priori detection rules, reported here so they cannot be "
    f"chosen post hoc: the mean-bias summary flags an error if |mean bias| > "
    f"{f1(P['bias_threshold'])} mmHg; the Bland\u2013Altman regression flags if "
    "the slope 95% confidence interval (CI) excludes 0; Deming and "
    "Passing\u2013Bablok flag if the slope 95% CI excludes 1; and the CCC "
    f"scale shift flags if |v \u2212 1| > {f2(P['v_threshold'])}. Strength of "
    "agreement was interpreted using published CCC criteria " +
    C.cite("mcbride2005") + ".")

add_heading_styled("2.3. Dynamic response and the fast-flush test", level=2)
add_para_with_refs(
    "The fluid-filled catheter\u2013transducer system behaves as a "
    "second-order system characterised by a natural frequency f_n and a "
    "damping coefficient \u03b6 " + C.cite("gardner1981") + ". We modelled its "
    "transfer function H(f) = 1/[1 \u2212 (f/f_n)\u00b2 + i\u00b72\u03b6(f/f_n)] "
    "and applied it to the Fourier harmonics of synthetic arterial waveforms. "
    "Under-damping (low \u03b6, resonance near the arterial harmonics) causes "
    "systolic overshoot and PP over-estimation; over-damping attenuates PP. "
    "Both are gain errors on the pulsatile signal that zeroing cannot correct, "
    "and both are quantified at the bedside by the fast-flush (square-wave) "
    "test " + C.cite("kleinman1992", "romagnoli2014") + ".")

add_heading_styled("2.4. Simulation design and reproducibility", level=2)
add_para_with_refs(
    f"All data in this study are simulated, not measured in patients. Static "
    f"scenarios comprised n = {P['n_static']} paired systolic pressures drawn "
    f"uniformly over {P['sbp_low']}\u2013{P['sbp_high']} mmHg with Gaussian "
    f"measurement noise (SD = {f1(P['noise_sd'])} mmHg): S1 offset only "
    f"(+{f1(P['offset_mmHg'])} mmHg, gain 1.0); S2 ideal zeroing (offset "
    f"removed, gain 1.0); S3 uncompensated gain error (gain {f2(P['gain'])}); "
    "and S4 the same gain error with a compensating negative offset chosen so "
    "the mean difference is approximately zero. Dynamic scenarios passed "
    "synthetic waveforms through optimal, under-damped and over-damped "
    "systems. A range-dependence experiment sampled one fixed device (5% gain "
    "error) over pressure ranges of increasing width. The random seed, all "
    "parameters and the full pipeline (simulate \u2192 analyse \u2192 figures "
    "\u2192 manuscript) are provided in the public repository so that a third "
    "party can regenerate every number, table and figure from a clean clone.")
add_para_with_refs(
    "Because all data are computer-generated, the study involved no human "
    "participants and no animals; ethics committee approval and informed "
    "consent were therefore not applicable.")
add_para_with_refs(
    "Use of artificial-intelligence tools: the simulation and analysis code, "
    "the figures, and drafts of the text were prepared with the assistance of "
    "an AI coding assistant (Devin; Cognition AI, San Francisco, California, "
    "USA). The authors reviewed and verified all code, numerical results and "
    "statements, and take full responsibility for the content of the article.")

# ══════════════════════════════════════════════════════════════════
# 3. RESULTS
# ══════════════════════════════════════════════════════════════════
add_heading_styled("3. Results", level=1)

add_heading_styled("3.1. Static scenarios", level=2)
add_para_with_refs(
    f"Concordance plots for the four static scenarios are shown in Fig. 1 and "
    f"the full metrics in Table 1. Ideal zeroing (S2) gave near-perfect "
    f"agreement (mean bias {signed(st['S2_zeroed_ideal']['bias'])} mmHg, "
    f"CCC {f3(st['S2_zeroed_ideal']['ccc'])}, v "
    f"{f3(st['S2_zeroed_ideal']['v'])}). An uncompensated 10% gain error (S3) "
    f"was obvious on every analysis, including the mean bias "
    f"({signed(st['S3_gain_uncompensated']['bias'])} mmHg): gain error is not "
    "invisible to a Bland\u2013Altman analysis.")
add_figure(
    "Figure 1. Device-versus-reference concordance for the four static "
    "scenarios (dashed line = identity). Each panel shows the CCC, the CCC "
    "scale shift v, and the Bland\u2013Altman mean bias. S4 has a near-zero mean "
    "bias despite a 10% gain error.")

add_para_with_refs(
    f"The decisive case is S4, where a compensating offset makes the mean bias "
    f"only {signed(st['S4_gain_masked']['bias'])} mmHg, within the "
    f"\u00b1{f1(P['bias_threshold'])} mmHg acceptance band, so the minimal "
    "Bland\u2013Altman summary does not flag any problem. Every "
    "proportional-bias\u2013aware analysis nonetheless detects the hidden gain "
    f"error: the Bland\u2013Altman regression slope is "
    f"{f3(st['S4_gain_masked']['prop_slope'])} (95% CI "
    f"{ci(st['S4_gain_masked']['prop_slope_lo'], st['S4_gain_masked']['prop_slope_hi'])}), "
    f"the Deming slope {f3(st['S4_gain_masked']['deming_slope'])} (95% CI "
    f"{ci(st['S4_gain_masked']['deming_lo'], st['S4_gain_masked']['deming_hi'])}), "
    f"the Passing\u2013Bablok slope {f3(st['S4_gain_masked']['pb_slope'])} "
    f"(95% CI {ci(st['S4_gain_masked']['pb_lo'], st['S4_gain_masked']['pb_hi'])}), "
    f"and the CCC scale shift v = {f3(st['S4_gain_masked']['v'])}. The "
    "detection pattern across all scenarios is summarised in Fig. 2, and the "
    "difference-versus-mean plots for S2 and S4 in Fig. 3.")
add_figure(
    "Figure 2. Which reported analysis detects the error in each scenario "
    "(green = detected, grey = missed). In S4 the mean-bias summary misses the "
    "gain error that every proportional-bias\u2013aware analysis detects.")
add_figure(
    "Figure 3. Bland\u2013Altman difference-versus-mean plots. In S2 the "
    "regression slope is flat; in S4 the slope is clearly positive despite a "
    "near-zero mean bias, revealing the masked proportional (gain) error.")

add_heading_styled("3.2. Dynamic-response scenarios", level=2)
add_para_with_refs(
    f"Dynamic-response metrics are given in Table 2 and illustrated in Fig. 4. "
    f"The optimal system reproduced PP faithfully (PP ratio "
    f"{f2(dy['optimal_pp']['mean_ratio'])}). Under-damping produced systolic "
    f"overshoot and inflated PP by "
    f"{round((dy['underdamped_pp']['mean_ratio']-1)*100)}% (PP ratio "
    f"{f2(dy['underdamped_pp']['mean_ratio'])}, CCC scale shift v = "
    f"{f2(dy['underdamped_pp']['v'])}); over-damping attenuated PP by "
    f"{round((1-dy['overdamped_pp']['mean_ratio'])*100)}% (PP ratio "
    f"{f2(dy['overdamped_pp']['mean_ratio'])}). These are gain errors on the "
    "pulsatile signal that survive zeroing. Because the distortion is "
    "frequency-dependent (it varies with heart rate rather than with pressure "
    "amplitude), it maps only partially onto the amplitude-proportional model "
    "underlying the static regression statistics, which is why it is best "
    "characterised directly by the fast-flush test parameters (f_n, \u03b6).")
add_figure(
    "Figure 4. Dynamic response of the catheter\u2013transducer system. (A) "
    "Frequency response of optimal, under-damped and over-damped systems with "
    "the arterial harmonics overlaid. (B) Example waveforms. (C) Measured "
    "versus true pulse pressure, with the mean PP ratio per system.")

add_heading_styled("3.3. Range-dependence of the CCC", level=2)
add_para_with_refs(
    f"For a single device with a fixed 5% gain error, the CCC rose from "
    f"{f2(rg['ccc'][0])} when sampled over a narrow pressure range "
    f"({int(rg['range_width'][0])} mmHg wide) to {f2(rg['ccc'][-1])} over a "
    f"wide range ({int(rg['range_width'][-1])} mmHg), while the scale shift v "
    "remained close to its true value (see Figure, Supplemental Digital "
    "Content 2, which shows the range-dependence of the CCC). The CCC "
    "therefore should be "
    "reported together with the sampled pressure range; the structural "
    "components (C_b, v) are more transportable across studies " +
    C.cite("nickerson1997") + ".")
add_sdc(
    "Supplemental Digital Content 2. Range-dependence of the CCC. For one "
    "fixed device, the CCC and C_b increase as the sampled pressure range "
    "widens, whereas the scale shift v stays close to the true gain ratio.")

# ══════════════════════════════════════════════════════════════════
# 4. DISCUSSION
# ══════════════════════════════════════════════════════════════════
add_heading_styled("4. Discussion", level=1)
add_para_with_refs(
    "Our central finding is narrow and, we believe, defensible: the "
    "mean-bias\u2013plus\u2013limits-of-agreement summary that dominates "
    "device-validation reporting can miss a clinically relevant gain error "
    "when a coincidental offset cancels its effect on the mean, whereas the "
    "Bland\u2013Altman difference-versus-mean regression " +
    C.cite("blandaltman1999") + ", Deming " + C.cite("linnet1990") +
    " and Passing\u2013Bablok " + C.cite("passingbablok1983") + " regression, "
    "and the CCC scale shift " + C.cite("lin2000") + " all detect it. This is "
    "a critique of common reporting practice, not of the Bland\u2013Altman "
    "method itself.")

add_heading_styled("4.1. Recommendations for validation reporting", level=2)
add_para_with_refs(
    "Validation studies of arterial pressure and derived monitors " +
    C.cite("kim2014", "joosten2017") + " should therefore report, in addition "
    "to mean bias and limits of agreement: (i) the Bland\u2013Altman regression "
    "slope with its CI (or, equivalently, a Deming or Passing\u2013Bablok "
    "slope); (ii) the CCC with its decomposition into r, C_b, u and v; and "
    "(iii) the sampled pressure range, because the CCC is range-dependent " +
    C.cite("nickerson1997", "barnhart2007") + ". Notably, C_b alone is "
    f"relatively insensitive to a pure gain error (in S4, C_b was "
    f"{f3(st['S4_gain_masked']['C_b'])} despite v = "
    f"{f3(st['S4_gain_masked']['v'])}); the scale shift v should be reported "
    "explicitly. These additions cost nothing beyond a few lines of analysis "
    "and would let regulators and clinicians " + C.cite("odor2017") +
    " distinguish offset-corrected agreement from genuine gain accuracy.")

add_heading_styled("4.2. Dynamic response is a distinct, clinical gain error", level=2)
add_para_with_refs(
    "The dynamic-response error is specific to fluid-filled systems and is "
    "routinely encountered at the bedside as under-damping (air bubbles, long "
    "compliant tubing) or over-damping (clots, kinks) " +
    C.cite("gardner1981", "romagnoli2014") + ". Because it is "
    "frequency-dependent, it is not fully captured by static "
    "method-comparison statistics and is best assessed directly with the "
    "fast-flush test, from which f_n and \u03b6 are read " +
    C.cite("kleinman1992") + ". We therefore recommend that a fast-flush "
    "dynamic-response check accompany any accuracy statement for a "
    "fluid-filled arterial line; pulse pressure is the sensitive readout, "
    "because it is proportional to gain but independent of offset.")

add_heading_styled("4.3. Implications for sensor design", level=2)
add_para_with_refs(
    "The reason zeroing is still performed today is that it corrects a "
    "setup-specific offset in real time, a role that no retrospective "
    "method-comparison statistic can fill. This also points to the way "
    "forward: because zeroing addresses only the operational offset problem, "
    "designing the offset sources out of the hardware removes the need to zero "
    "at all, leaving gain and dynamic response as the residual design and "
    "validation problems.")
add_para_with_refs(
    "The offset that zeroing corrects can also be removed by design. "
    "Catheter-tip micro-electro-mechanical systems (MEMS) sensors abolish the "
    "hydrostatic column " + C.cite("hasenkamp2012", "song2020") + "; absolute "
    "sensors with barometric compensation remove the atmospheric reference; "
    "and self-calibrating MEMS references limit drift " + C.cite("kang2022") +
    ". High-fidelity pressure wires already demonstrate accurate catheter-based "
    "pressure measurement " + C.cite("scalia2023") + ". With offset removed by "
    "design and gain verified by accurate PP reproduction, the residual "
    "systematic error is expressed entirely in v, giving a concrete design "
    "target (v \u2248 1, C_b \u2265 0.99 without calibration) " +
    C.cite("mcbride2005") + ". Modern piezoresistive MEMS sensors achieve "
    "non-linearity well below 0.1% of full scale " + C.cite("barlian2009") +
    ", supporting the assumption that gain verified over the pulsatile range "
    "generalises across the physiological range.")

add_heading_styled("4.4. Extension to derived haemodynamic monitors", level=2)
add_para_with_refs(
    "The offset-versus-gain distinction extends to derived monitors whose "
    "auto-calibration routines re-optimise a setpoint (an offset correction) "
    "without correcting the gain of the pressure- or "
    "impedance-to-flow conversion " +
    C.cite("chatterjee2009", "ameloot2015", "squara2007", "manecke2005") +
    ". Reporting the scale shift v for these devices would make their "
    "dependence on calibration explicit.")

add_heading_styled("4.5. Limitations", level=2)
add_para_with_refs(
    "This is a simulation study; the data are synthetic and chosen to isolate "
    "specific error structures, and they are not a substitute for a "
    "prospective clinical comparison against an invasive reference of stated "
    "precision " + C.cite("cecconi2009") + ". The static model assumes "
    "sensor linearity, and the dynamic model is a single second-order "
    "approximation. The value of the work is to make explicit, and "
    "reproducibly quantify, which reported analyses detect a residual gain "
    "error, a prelude to rather than a replacement for empirical validation.")

# ══════════════════════════════════════════════════════════════════
# 5. CONCLUSION
# ══════════════════════════════════════════════════════════════════
add_heading_styled("5. Conclusion", level=1)
add_para_with_refs(
    "Zero calibration corrects offset but not gain. A mean-bias\u2013plus"
    "\u2013limits-of-agreement summary can miss a residual gain error when an "
    "offset masks it, whereas Bland\u2013Altman regression, Deming and "
    "Passing\u2013Bablok regression, and the CCC scale shift detect it. Dynamic"
    "-response error is a distinct, frequency-dependent gain error diagnosed "
    "by the fast-flush test. We recommend that arterial pressure validation "
    "studies report a proportional-bias\u2013aware analysis, the CCC "
    "decomposition with the sampled range, and an explicit dynamic-response "
    "check.")

# ══════════════════════════════════════════════════════════════════
# DECLARATIONS (conflicts of interest and funding are stated on the title
# page, as required by Blood Pressure Monitoring)
# ══════════════════════════════════════════════════════════════════
add_heading_styled("Acknowledgements", level=1)
add_para("[To be completed by the authors, or state \u201cnone\u201d.]")
add_heading_styled("Data availability", level=1)
add_para(
    "All simulation code and generated data are openly available in the public "
    "replication repository (https://github.com/bougtoir/bpm-zero-calibration). "
    "Every number, table and figure in this article can be regenerated from a "
    "clean clone by running the analysis pipeline.")

doc.add_page_break()

# ══════════════════════════════════════════════════════════════════
# REFERENCES (numbered in order of first appearance; in-text as [n])
# ══════════════════════════════════════════════════════════════════
add_heading_styled("References", level=1)
missing = C.check_all_cited()
for idx, ref in enumerate(C.ordered_references(), start=1):
    p = doc.add_paragraph()
    run = p.add_run(f"{idx}. {ref}")
    run.font.name = "Times New Roman"
    run.font.size = Pt(10)
    p.paragraph_format.space_after = Pt(3)
    p.paragraph_format.line_spacing = 1.5
    p.paragraph_format.first_line_indent = Cm(-0.9)
    p.paragraph_format.left_indent = Cm(0.9)

doc.add_page_break()

# ══════════════════════════════════════════════════════════════════
# TABLE 1 — static metrics (built from summary; no vertical rules)
# ══════════════════════════════════════════════════════════════════
add_heading_styled("Table 1", level=1)
add_para("Table 1. Method-comparison metrics for the four static scenarios "
         f"(n = {P['n_static']} paired measurements each).",
         bold=True, italic=True)

t1_headers = ["Scenario", "Mean bias\n(mmHg)", "95% LoA\n(mmHg)", "PE (%)",
              "BA reg. slope\n(95% CI)", "Deming slope\n(95% CI)",
              "P\u2013B slope\n(95% CI)", "CCC", "C_b", "v"]
scen_names = {
    "S1_offset_only": "S1 offset only",
    "S2_zeroed_ideal": "S2 zeroed (ideal)",
    "S3_gain_uncompensated": "S3 gain error",
    "S4_gain_masked": "S4 gain masked",
}
table = doc.add_table(rows=1 + len(scen_names), cols=len(t1_headers))
horizontal_borders(table)
for i, h in enumerate(t1_headers):
    cell = table.rows[0].cells[i]
    cell.text = h
    for p in cell.paragraphs:
        for r in p.runs:
            r.bold = True; r.font.size = Pt(8); r.font.name = "Times New Roman"

for row_idx, (key, label) in enumerate(scen_names.items(), start=1):
    d = st[key]
    row = [
        label,
        signed(d["bias"]),
        f"{d['loa_lower']:.1f} to {d['loa_upper']:.1f}",
        f1(d["pe"]),
        f"{d['prop_slope']:.3f}\n({d['prop_slope_lo']:.3f}, {d['prop_slope_hi']:.3f})",
        f"{d['deming_slope']:.3f}\n({d['deming_lo']:.3f}, {d['deming_hi']:.3f})",
        f"{d['pb_slope']:.3f}\n({d['pb_lo']:.3f}, {d['pb_hi']:.3f})",
        f3(d["ccc"]), f3(d["C_b"]), f3(d["v"]),
    ]
    for col_idx, txt in enumerate(row):
        cell = table.rows[row_idx].cells[col_idx]
        cell.text = txt
        for p in cell.paragraphs:
            for r in p.runs:
                r.font.size = Pt(8); r.font.name = "Times New Roman"

add_para(
    "BA = Bland\u2013Altman; CI = confidence interval; LoA = limits of agreement; "
    "PE = percentage error; P\u2013B = Passing\u2013Bablok; CCC = concordance "
    "correlation coefficient; C_b = bias-correction factor; v = scale shift. "
    "S4 has a near-zero mean bias yet a clearly non-zero regression, Deming and "
    "Passing\u2013Bablok slope and v > 1, i.e. a gain error hidden from the "
    "mean-bias summary.", italic=True)
doc.add_page_break()

# ══════════════════════════════════════════════════════════════════
# TABLE 2 — dynamic metrics (built from summary; no vertical rules)
# ══════════════════════════════════════════════════════════════════
add_heading_styled("Table 2", level=1)
add_para("Table 2. Dynamic-response metrics for pulse pressure (PP) and "
         "systolic pressure (SBP).", bold=True, italic=True)

t2_headers = ["System (f_n, \u03b6)", "PP ratio", "PP mean bias\n(mmHg)",
              "CCC (PP)", "v (PP)", "SBP mean bias\n(mmHg)"]
_ds = P["dyn_systems"]
dyn_rows = {
    "optimal": f"Optimal ({f1(_ds['optimal']['fn'])} Hz, {f2(_ds['optimal']['zeta'])})",
    "underdamped": f"Underdamped ({f1(_ds['underdamped']['fn'])} Hz, {f2(_ds['underdamped']['zeta'])})",
    "overdamped": f"Overdamped ({f1(_ds['overdamped']['fn'])} Hz, {f2(_ds['overdamped']['zeta'])})",
}
table2 = doc.add_table(rows=1 + len(dyn_rows), cols=len(t2_headers))
horizontal_borders(table2)
for i, h in enumerate(t2_headers):
    cell = table2.rows[0].cells[i]
    cell.text = h
    for p in cell.paragraphs:
        for r in p.runs:
            r.bold = True; r.font.size = Pt(8); r.font.name = "Times New Roman"

for row_idx, (key, label) in enumerate(dyn_rows.items(), start=1):
    pp = dy[f"{key}_pp"]; sbp = dy[f"{key}_sbp"]
    row = [label, f2(pp["mean_ratio"]), signed(pp["bias"]),
           f3(pp["ccc"]), f3(pp["v"]), signed(sbp["bias"])]
    for col_idx, txt in enumerate(row):
        cell = table2.rows[row_idx].cells[col_idx]
        cell.text = txt
        for p in cell.paragraphs:
            for r in p.runs:
                r.font.size = Pt(8); r.font.name = "Times New Roman"

add_para(
    "PP ratio = mean(measured PP / true PP); f_n = natural frequency; "
    "\u03b6 = damping coefficient. Under-damping inflates and over-damping "
    "attenuates pulse pressure; the mean arterial (DC) level is preserved, so "
    "zeroing does not correct these errors.", italic=True)
doc.add_page_break()

# ══════════════════════════════════════════════════════════════════
# FIGURE LEGENDS (figures are submitted as separate files)
# ══════════════════════════════════════════════════════════════════
add_heading_styled("Figure legends", level=1)
for legend in FIG_LEGENDS:
    add_para(legend)

# ══════════════════════════════════════════════════════════════════
# SUPPLEMENTAL DIGITAL CONTENT (separate files; not counted in the limit)
# ══════════════════════════════════════════════════════════════════
add_heading_styled("Supplemental Digital Content", level=1)
for legend in SDC_LIST:
    add_para(legend)

# ---- finalise the title-page word count (title page to last reference;
#      tables, figure legends and Supplemental Digital Content are excluded) --
def _nwords(s):
    return len(re.findall(r"[A-Za-z0-9][A-Za-z0-9'\-]*", s))


_wc = sum(_nwords(_p.text) for _p in doc.paragraphs)
_wc -= sum(_nwords(x) for x in FIG_LEGENDS + SDC_LIST)
_wc -= _nwords("Figure legends") + _nwords("Supplemental Digital Content")
wc_run.text = f"~{_wc}"

doc.save(OUTPATH)
print(f"English BPM manuscript saved: {OUTPATH}")
print(f"References cited: {len(C.order)} / {len(REFDB)} in database")
print(f"Main figures: {len(FIG_LEGENDS)}  SDC items: {len(SDC_LIST)}")
if missing:
    print(f"WARNING: uncited references in database: {missing}")
